language: python
python:
- '2.7'
- '3.5'
- '3.6'
matrix:
  include:
  - python: '3.7'
    dist: xenial
install:
- python setup.py install
- pip install coveralls
script:
- coverage run --source=darklyrics setup.py test
- coveralls
deploy:
  provider: pypi
  user: res0nance
  on:
    tags: true
    branch: master
    python: '3.6'
  password:
    secure: EZSPQFN0IJe3qBzzZvu3rlzb5fgcHkILOl4+o+Tub5+WOUeUsvjADZuWf47TzbwO80wMEbLy/DdiSt69E0F+BHra690MGofpyk5qMYuYiAfavYIJVe/ua0Q+5WLabwpr78vMR6FXFho224yYwApYREiPa16nxm91j2tRYZCYrIkAbjk0J9p+kKn1XPSXkT+C4es4jC0iaMLn7nA+G2HfAR+NzeSDV84khsK+bUNAwGjsy/vUqgtzJFcVSwP8DPxcQ3NrPECTkq4eWM8fye1NLTCyszMNLQQDGnxyVYqPK3f8r8G8jr5++KgeVxg2dBFj4/D/V6IVOjOO5AXG3J6eWDc1FMSym5Ry1valx1gLzWhZrebKvDHQkOGl3fZdDKECsqqf95VoesEaecve+JxB8NVEL6R/zCEZ7u4Mn78njjuN1hERgsMeBvwlj5+yUmvjkmdHrX4t9ejWx2zOpaEHblTwM1PVIfbfU0ubd0wlZcUhYkqK63IkoskAxPfmEOg4sv0nBh05vV+CIEm4KoTRblvTyPD+6JtesuqyYT6dUnUw9/dcOZtqapjv9w4vUG5UAJACqc4X60Ckv0un+GVwYe956XrT2wqvDrqN4/gpn0oDetPdMSKswzzpKwzCGRFxHzwId7QK68/I5IeQkpCJ4ae0flt3XDOHKU67lIn8gVo=
