language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install: 
  - python setup.py install
  - pip install python-coveralls
  - pip install coverage
script:
  - coverage run --source=darklyrics setup.py test
  - coveralls
